# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: logincreds
- name: va
  value: $[variables.azuser]
- name: vb
  value: $[variables.azpwd]
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "a=$(va)"
      echo "b=$(vb)"
      echo "user=$(azuser)"
      echo "passwd=$(azpwd)"
      echo "mytext=$(plain)"
  env:
    myuser: $(azuser)
    mypass: $(azpwd)
- task: Bash@3
  inputs:
    script: printenv | grep my*