# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: logincreds
- name: va
  value: $[variables.azuser]
- name: vb
  value: $[variables.azpwd]
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $(Build.DefinitionName)
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'PS-Subscription'
    KeyVaultName: 'mykeyvault0712'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  inputs:
    script: 'echo $(Password) > secret.txt'

- task: CopyFiles@2
  inputs:
    Contents: 'secret.txt'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'